More than a little local testing with nektos/act

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -23,16 +23,17 @@ jobs:
       - name: Run unit tests
         run: npm run test
       - name: Run action
-        id: get_access_token
+        id: get_token
         uses: ./
         with:
           app_id: ${{ secrets.HEROKU_ALL_REPO_READ_APP_ID }}
           private_key: ${{ secrets.HEROKU_ALL_REPO_READ_PRIVATE_KEY }}
           installation_id: ${{ secrets.HEROKU_ALL_REPO_READ_INSTALLATION_ID }}
       - name: Action successful
-        uses: actions/github-script@v7
-        with:
-          script: |
-            if "${{ steps.get_access_token.outputs.success }}" !== "true" || !"${{ steps.get_access_token.outputs.app_token }}" {
-              core.setFailed('App token action failed');
-            }
+        run: |
+          if [[ "${{ steps.get_token.outcome }}" == "success" && ! -z "${{ steps.get_token.outputs.app_token }}" ]]; then
+            echo "✅ App token action successful!";
+          else
+            echo "❌ App token action failed!";
+            exit 1;
+          fi
